
import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author vinas
 */
public class transactionFrame extends javax.swing.JFrame {
private double priceSize, totalPrice, pizzaQTY;
    /**
     * Creates new form transactionFrame
     */
    public transactionFrame() {
        initComponents();
        systemUser.setText(loginFrame.setUsername);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        cash = new javax.swing.JTextField();
        total = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        cancel = new javax.swing.JButton();
        ham = new javax.swing.JCheckBox();
        pep = new javax.swing.JCheckBox();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        qty = new javax.swing.JTextField();
        compute = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        change = new javax.swing.JLabel();
        computeChange = new javax.swing.JButton();
        save = new javax.swing.JButton();
        size = new javax.swing.JComboBox<>();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        systemUser = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(202, 228, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 14)); // NOI18N
        jLabel1.setText("====================================");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 520, 400, 30));

        jLabel2.setFont(new java.awt.Font("Viner Hand ITC", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 51, 0));
        jLabel2.setText("Pizza Ordering System");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 10, 270, 30));

        cash.setFont(new java.awt.Font("Microsoft JhengHei", 0, 12)); // NOI18N
        jPanel1.add(cash, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 310, 220, 30));

        total.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 18)); // NOI18N
        total.setForeground(new java.awt.Color(204, 102, 0));
        total.setText("0.00");
        jPanel1.add(total, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 270, -1, 30));

        jLabel4.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 18)); // NOI18N
        jLabel4.setText("Toppings :");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 100, -1, 30));

        cancel.setBackground(new java.awt.Color(153, 153, 153));
        cancel.setFont(new java.awt.Font("Microsoft YaHei", 1, 12)); // NOI18N
        cancel.setText("Cancel");
        cancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelActionPerformed(evt);
            }
        });
        jPanel1.add(cancel, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 420, 90, 30));

        ham.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 14)); // NOI18N
        ham.setText("Ham");
        ham.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hamActionPerformed(evt);
            }
        });
        jPanel1.add(ham, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 100, -1, 30));

        pep.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 14)); // NOI18N
        pep.setText("Pepperoni");
        pep.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pepActionPerformed(evt);
            }
        });
        jPanel1.add(pep, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 100, -1, 30));

        jLabel5.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 18)); // NOI18N
        jLabel5.setText("Quantity : ");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 140, -1, 30));

        jLabel6.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 18)); // NOI18N
        jLabel6.setText("Pizza Size :");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 60, -1, 30));

        jLabel7.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 18)); // NOI18N
        jLabel7.setText("CASH :");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 310, -1, 30));

        jLabel8.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 18)); // NOI18N
        jLabel8.setText("TOTAL :");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 270, -1, 30));

        qty.setFont(new java.awt.Font("Microsoft JhengHei", 0, 12)); // NOI18N
        jPanel1.add(qty, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 140, 220, 30));

        compute.setBackground(new java.awt.Color(252, 252, 252));
        compute.setFont(new java.awt.Font("Microsoft YaHei", 1, 12)); // NOI18N
        compute.setText("COMPUTE");
        compute.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                computeActionPerformed(evt);
            }
        });
        jPanel1.add(compute, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 180, 220, 30));

        jLabel9.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 18)); // NOI18N
        jLabel9.setText("CHANGE :");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 390, -1, 30));

        change.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 18)); // NOI18N
        change.setForeground(new java.awt.Color(204, 102, 0));
        change.setText("0.00");
        jPanel1.add(change, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 390, -1, 30));

        computeChange.setBackground(new java.awt.Color(252, 252, 252));
        computeChange.setFont(new java.awt.Font("Microsoft YaHei", 1, 12)); // NOI18N
        computeChange.setText("Compute Change");
        computeChange.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                computeChangeActionPerformed(evt);
            }
        });
        jPanel1.add(computeChange, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 350, 220, 30));

        save.setBackground(new java.awt.Color(0, 153, 51));
        save.setFont(new java.awt.Font("Microsoft YaHei", 1, 12)); // NOI18N
        save.setForeground(new java.awt.Color(255, 255, 255));
        save.setText("SAVE Transaction");
        save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveActionPerformed(evt);
            }
        });
        jPanel1.add(save, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 420, 220, 30));

        size.setBackground(new java.awt.Color(252, 252, 252));
        size.setFont(new java.awt.Font("Microsoft YaHei UI", 0, 14)); // NOI18N
        size.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Small", "Medium", "Large" }));
        jPanel1.add(size, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 60, 220, 30));

        jLabel11.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 14)); // NOI18N
        jLabel11.setText("====================================");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 230, 400, 30));

        jLabel12.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 14)); // NOI18N
        jLabel12.setText("====================================");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 460, 400, 30));

        jLabel13.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 18)); // NOI18N
        jLabel13.setText("HELLO :");
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 490, -1, 30));

        systemUser.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 18)); // NOI18N
        systemUser.setForeground(new java.awt.Color(204, 102, 0));
        systemUser.setText("System User");
        jPanel1.add(systemUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 490, -1, 30));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 550));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelActionPerformed
        int answerCancel;
        
        answerCancel = JOptionPane.showConfirmDialog(null, "cancel?");
        if (answerCancel == JOptionPane.YES_OPTION){
            setClear();
        }
    }//GEN-LAST:event_cancelActionPerformed

    private void hamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hamActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_hamActionPerformed

    private void pepActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pepActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pepActionPerformed

    private void computeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_computeActionPerformed
        pizzaQTY = Double.parseDouble(qty.getText());
        
        if(size.getSelectedItem().equals("Small")){
            priceSize = 100;
            getTotal();
        } else if(size.getSelectedItem().equals("Medium")){
            priceSize = 200;
            getTotal();
        } else if(size.getSelectedItem().equals("Large")){
            priceSize = 300;
            getTotal();
        }
    }//GEN-LAST:event_computeActionPerformed
    
    private void setClear(){
        qty.setText("");
        cash.setText("");
        total.setText("0.00");
        change.setText("0.00");
        pep.setSelected(false);
        ham.setSelected(false);
        
    }
    
    private void getTotal(){
        if (pep.isSelected() && ham.isSelected()){
            totalPrice = (priceSize + 160 + 100)*pizzaQTY;
            total .setText(Double.toString(totalPrice));
        } else if (pep.isSelected()){
            totalPrice = (priceSize + 160)*pizzaQTY;
            total .setText(Double.toString(totalPrice));
        } else if (ham.isSelected()){
            totalPrice = (priceSize + 100)*pizzaQTY;
            total .setText(Double.toString(totalPrice));
        } else {
            totalPrice = (priceSize)*pizzaQTY;
            total .setText(Double.toString(totalPrice));
        }
    }
    
    private void computeChangeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_computeChangeActionPerformed
        double getChange, cashG, totalC;
        cashG = Double.parseDouble(cash.getText());
        totalC = Double.parseDouble(total.getText());
        
        getChange = cashG - totalC;
        change.setText(Double.toString(getChange));
    }//GEN-LAST:event_computeChangeActionPerformed

    private void saveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_saveActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(transactionFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(transactionFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(transactionFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(transactionFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new transactionFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cancel;
    private javax.swing.JTextField cash;
    private javax.swing.JLabel change;
    private javax.swing.JButton compute;
    private javax.swing.JButton computeChange;
    private javax.swing.JCheckBox ham;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JCheckBox pep;
    private javax.swing.JTextField qty;
    private javax.swing.JButton save;
    private javax.swing.JComboBox<String> size;
    private javax.swing.JLabel systemUser;
    private javax.swing.JLabel total;
    // End of variables declaration//GEN-END:variables
}
